[tool.poetry]
name = "symmetry"
version = "0.1.0"
description = ""
authors = ["AlexBlandin <20842735+AlexBlandin@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
